# Generated by Django 5.1.6 on 2025-02-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrohub_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
