# Generated by Django 5.1.6 on 2025-02-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrohub_api', '0002_customuser_bio_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
